### ISSUE TITLE
Release 0.5.0 on pypi

### ISSUE THREAD

**Issue by lumannnn** [disqus/disqus-python#26]
Hey there :)

I'm curious. Do you happen to know when the next version (0.5.0 as the https://github.com/disqus/disqus-python/blob/master/CHANGES states) will be released?
I'd like to use this package but I do not want to introduce the ``simplejson`` dependency.

Thank you in advance and best regards.

**Comment by MarkusHackspacher** [comment]
I thing I have get a old version, and the new one, because in line 15  is no import httplib

```
# pip install disqus-python

$ python3 -c 'import disqusapi'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/disqusapi/__init__.py", line 15, in <module>
    import httplib
ImportError: No module named 'httplib'
```

**Comment by shackra** [comment]
@MarkusHackspacher that's because on Python 3 `httplib` was renamed to `http.client`
